
services:
  backend:
    build: .
    container_name: todo_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8002:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True