name: Django CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build containers
      run: docker compose build
      
    - name: Run makemigrations
      run: docker compose run --rm backend python manage.py makemigrations

    - name: Run migrate
      run: docker compose run --rm backend python manage.py migrate

    - name: Lint code with flake8
      run: docker compose run --rm backend flake8

    - name: Check code format with black
      run: docker compose run --rm backend black --check

    - name: Run tests
      run: docker compose run --rm backend pytest

    - name : Cleanup
      run: docker compose down -v
